name: Notify Discord on Push

on:
  push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Format and send commits to Discord
        uses: actions/github-script@v7
        with:
          script: |
            const webhook = process.env.DISCORD_WEBHOOK;
            const commits = context.payload.commits;
            const repo = context.payload.repository.full_name;
            const branch = context.payload.ref.replace('refs/heads/', '');

            let content = `🚀 **New push to \`${repo}\` on branch \`${branch}\`:**\n\n`;

            for (const commit of commits) {
              const shortId = commit.id.substring(0, 7);
              content += `🔸 [\`${shortId}\`](${commit.url}) ${commit.message} — _${commit.author.name}_\n`;
            }

            const payload = {
              content: content
            };

            await fetch(webhook, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload)
            });
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
